# Hyprland configuration overrides
# Add custom settings here

# Use single default monitor (see all monitors with: hyprctl monitors)
#monitor=,preferred,auto,1.6

# .config/hypr/monitors.conf
monitor=DP-1,3440x1440@59.97,0x0,1
monitor=eDP-1,1920x1080@60,3440x0,1

# .config/hypr/input.conf
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  kb_layout = ch
  kb_variant = de
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
  # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4

    # Enable the touchpad while typing
    # disable_while_typing = false

    # Left-click-and-drag with three fingers
    # drag_3fg = 1
  }
}
